### ISSUE TITLE
Can't bind to 'configs' since it isn't a known property of 'angular-telegram-login-widget'.

### ISSUE THREAD

**Issue by kopyl** [madmages/angular-telegram-login-widget#2]
Here is my code:

I get this error from Angular. Do you know how to fix it?

<angular-telegram-login-widget (load)="TGonLoad()" (loadError)="TGonLoadError()" (login)="TGonLogin($event)"
[botName]=botname [configs]=WidgetConfiguration></angular-telegram-login-widget>

**Comment by kopyl** [comment]
I found the culprit. You specified `configs` instead of `config` on https://github.com/madmages/angular-telegram-login-widget/tree/master/projects/angular-telegram-login-widget#configurations

**Comment by madmages** [comment]
docs fixed
